// <auto-generated />
using System;
using Homework6.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Homework6.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    [Migration("20230506131444_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.3.23174.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Homework6.Models.Analysis", b =>
                {
                    b.Property<int>("AnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("an_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnId"));

                    b.Property<decimal>("AnCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("an_cost");

                    b.Property<int>("AnGroupId")
                        .HasColumnType("int")
                        .HasColumnName("an_group");

                    b.Property<string>("AnName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("an_name");

                    b.Property<decimal>("AnPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("an_price");

                    b.HasKey("AnId");

                    b.HasIndex("AnGroupId");

                    b.ToTable("Analyzes");
                });

            modelBuilder.Entity("Homework6.Models.Group", b =>
                {
                    b.Property<int>("GrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("gr_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrId"));

                    b.Property<string>("GrName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gr_name");

                    b.Property<decimal>("GrTemp")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)")
                        .HasColumnName("gr_temp");

                    b.HasKey("GrId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Homework6.Models.Order", b =>
                {
                    b.Property<int>("OrdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ord_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdId"));

                    b.Property<int>("OrdAnId")
                        .HasColumnType("int")
                        .HasColumnName("ord_an");

                    b.Property<DateTime>("OrdDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ord_datetime");

                    b.HasKey("OrdId");

                    b.HasIndex("OrdAnId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Homework6.Models.Analysis", b =>
                {
                    b.HasOne("Homework6.Models.Group", "AnGroup")
                        .WithMany("Analyzes")
                        .HasForeignKey("AnGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnGroup");
                });

            modelBuilder.Entity("Homework6.Models.Order", b =>
                {
                    b.HasOne("Homework6.Models.Analysis", "OrdAn")
                        .WithMany("Orders")
                        .HasForeignKey("OrdAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdAn");
                });

            modelBuilder.Entity("Homework6.Models.Analysis", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Homework6.Models.Group", b =>
                {
                    b.Navigation("Analyzes");
                });
#pragma warning restore 612, 618
        }
    }
}
